[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.11.3,<0.12" ]

[project]
name = "navanalysis-lcm"
version = "0.1.5"
description = "Analysis tools for LCM logs."
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [ { name = "IS4S", email = "pntos@is4s.com" } ]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "aspn23",
    "aspn23-lcm",
    "inu==1.1.0",
    "lcm>=1.5.1,<2",
    "matplotlib>=3.9.3",
    "navtk",
    "numpy",
    "pyyaml>=6.0.0",
    "scipy!=1.15.*; sys_platform=='darwin'",
    "scipy>=1.15.2; sys_platform!='darwin'",
    "tabulate>=0.9.0",
    "tomlkit>=0.13.0",
    "tqdm",
]
scripts.altitude = "navanalysis.lcm.scripts.plot_alt:main"
scripts.dt = "navanalysis.lcm.scripts.plot_dt:main"
scripts.get_imu_rotation = "navanalysis.lcm.scripts.get_imu_rotations:main"
scripts.imu = "navanalysis.lcm.scripts.plot_imu:main"
scripts.magnetometer = "navanalysis.lcm.scripts.plot_mag:main"
scripts.position = "navanalysis.lcm.scripts.plot_pos:main"
scripts.print_channels = "navanalysis.lcm.scripts.print_channels:main"
scripts.pva = "navanalysis.lcm.scripts.plot_pva:main"
scripts.range_rate = "navanalysis.lcm.scripts.plot_range_rate_to_point:main"
scripts.remove_channels = "navanalysis.lcm.scripts.remove_channels:main"
scripts.rename_channels = "navanalysis.lcm.scripts.rename_channels:main"
scripts.sort_log = "navanalysis.lcm.scripts.sort_log_by_time:main"
scripts.speed = "navanalysis.lcm.scripts.plot_speed:main"
scripts.stationary_imu = "navanalysis.lcm.scripts.plot_stationary_imu:main"
scripts.timespan = "navanalysis.lcm.scripts.get_time_range:main"
scripts.timestamps = "navanalysis.lcm.scripts.plot_time:main"
scripts.velocity = "navanalysis.lcm.scripts.plot_vel:main"

[tool.uv]
build-backend.module-name = "navanalysis.lcm"
